# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PunkBeer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PunkBeer
  pod 'ReachabilitySwift'
  pod 'Moya'
  pod 'Kingfisher'


  target 'PunkBeerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
